---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/tgw-create
      when: rosa_tgw_enabled | bool
    - name: roles/egress-vpc-create
      when: rosa_egress_vpc_enabled | bool
    - name: roles/vpc-create
      when: rosa_subnet_ids | default([]) | length == 0
    - name: roles/jumphost-create
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)
    - name: roles/proxy-create
      when:
        - (rosa_private_link | bool) and
          (proxy_enabled | default(False) | bool)
    - name: roles/cluster-create
    - name: roles/dns-resolver-create
      when: rosa_tgw_enabled | bool
    - name: roles/create-admin
    - name: roles/finish


- hosts:      "jumphost"
  connection: "ssh"
  remote_user: ec2-user
  vars:
    cluster_api: "{{ hostvars.localhost._cluster_info.cluster.api.url }}"
  roles:
    - name: roles/post-install
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)
