---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/cluster-delete
    - name: roles/sts-infra-delete
      when: rosa_sts | bool
    - name: roles/sts-operator-delete
      when: rosa_sts | bool
    - name: roles/jumphost-delete
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)
    - name: roles/vpc-delete
      when: rosa_subnet_ids | default([]) | length == 0



