---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/cluster-delete
    - name: roles/sts-infra-delete
    - name: roles/sts-operator-delete
    - name: roles/vpc-delete



