---
- name: what cluster am i creating?
  debug:
    msg: |
      ***************************************
      Preparing to create {{ cluster_name }}.
      This task may take up to an hour.
      ***************************************
    verbosity: 0

- when:
    - aws_account_id is not defined
    - rosa_sts | bool
  block:
    - name: get aws caller info for accountid
      aws_caller_info:
      register: _aws_caller_info

    - set_fact:
        aws_account_id: "{{ _aws_caller_info.account }}"

# do this better ... maybe better set during vpc creation and inherited.
- name: figure out list of subnets
  set_fact:
    _private_subnet_ids: "{{ _private_subnets.results | default([]) | json_query('[*].subnet.id') }}"
    _public_subnet_ids:  "{{ _public_subnets.results  | default([]) | json_query('[*].subnet.id') }}"
  when:
    - rosa_subnet_ids | length == 0
    - _private_subnets is defined or _public_subnets is defined
- set_fact:
    rosa_subnet_ids: "{{ rosa_subnet_ids | default(_private_subnet_ids + _public_subnet_ids) }}"
  when: rosa_subnet_ids | length == 0


# - name: check if the cluster already exists
#   command: "rosa describe cluster --cluster {{ cluster_name }}"
#   register: _cluster_exists
#   failed_when: false
#   changed_when: false

# - fail:
#     var: _cluster_exists

- name: create cluster
  rosa_cluster:
    name: "{{ cluster_name }}"
    private: "{{ rosa_private }}"
    private_link: "{{ rosa_private_link }}"
    sts: "{{ rosa_sts }}"
    aws_account_id: "{{ aws_account_id | default(omit) }}"
    machine_cidr: "{{ rosa_vpc_cidr }}"
    subnet_ids: "{{ rosa_subnet_ids | join(',') }}"

