---
# tasks file for roles/create_admin

- set_fact:
    rosa_admin_credentials: {}

- command: rosa create admin -c {{ cluster_name }} -p "{{ rosa_admin_password }}" -o json
  register: _create_admin
  failed_when: (_create_admin.rc != 0) and ("already has an admin" not in _create_admin.stderr)
  changed_when: _create_admin.rc == 0
  no_log: true
  when: rosa_create_admin




# - set_fact:
#     rosa_admin_credentials: "{{ _create_admin.stdout | from_json }}"
#   when: _create_admin.rc == 0

