---
- name: fetch transit gateway
  ec2_transit_gateway_info:
    filters:
      "tag:Name": "rosa-{{ cluster_name }}-tgw"
  register: _tgw

- name: detach VPC to transit gateway
  shell: |
    AWS_PAGER=""
    for TGW_A in $(aws ec2 describe-transit-gateway-vpc-attachments \
          --filters Name=transit-gateway-id,Values={{ _tgw.transit_gateways[0].transit_gateway_id }} \
          --query 'TransitGatewayVpcAttachments[*].TransitGatewayAttachmentId' \
          --output text | xargs)
      do
        aws ec2 delete-transit-gateway-vpc-attachment --transit-gateway-attachment-id $TGW_A
        while [ "$(aws ec2 describe-transit-gateway-vpc-attachments \
            --filters Name=transit-gateway-attachment-id,Values=$TGW_A \
            --query 'TransitGatewayVpcAttachments[*].State' \
            --output text)" != "deleted" ]; do
          echo "Waiting for transit gateway attachment to detach"
          sleep 5
        done
    done
  when: _tgw.transit_gateways | length > 0

- name: delete transit gateway
  ec2_transit_gateway:
    state: absent
    region: "{{ rosa_region }}"
    description: "rosa {{ cluster_name }} transit gateway"
    tags: { "Name": "rosa-{{ cluster_name }}-tgw" }
  when: _tgw.transit_gateways | length > 0
