---
- name: create nat gateway per public subnet (az)
  ec2_vpc_nat_gateway:
    subnet_id: "{{ item.subnet.id }}"
    state: present
    if_exist_do_not_create: yes
    wait: true
  register: _natgw

# - debug:
#     var: _natgw

- name: create private subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ _vpc.vpc.id }}"
    tags:
      Name: "private-{{ item.subnet.id }}"
    subnets: "{{ item.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ _natgw.nat_gateway_id }}"
