---
- name: Create a new transit gateway using defaults
  ec2_transit_gateway:
    state: present
    region: "{{ rosa_region }}"
    description: "rosa {{ cluster_name }} transit gateway"
    dns_support: yes
    tags: { "Name": "rosa-{{ cluster_name }}-tgw" }
    auto_associate: yes
    auto_propagate: yes
    # auto_attach: no
  register: _tgw

- set_fact:
    tgw_id: "{{ _tgw.transit_gateway.transit_gateway_id }}"
    tgw_arn: "{{ _tgw.transit_gateway.transit_gateway_arn }}"
    tgw_route_table: "{{ _tgw.transit_gateway.options.association_default_route_table_id }}"

- include_tasks: vpc.yml

- name: add default route to tgw for egress
  shell: |
    aws ec2 create-transit-gateway-route \
    --destination-cidr-block 0.0.0.0/0 \
    --transit-gateway-route-table-id {{ tgw_route_table }} \
    --transit-gateway-attachment-id {{ _tgw_attachment_id }}
  register: _tgw_rt
  failed_when: (_tgw_rt.rc != 0) and ("RouteAlreadyExists" is not in _tgw_rt.stderr)
  changed_when: _tgw_rt.rc == 0
