---
- name: what cluster am i deleting?
  debug:
    msg: |
      ***************************************
      Preparing to delete {{ cluster_name }}.
      This task may take up to an hour.
      ***************************************
    verbosity: 0

- name: delete cluster
  rosa_cluster:
    name: "{{ cluster_name }}"
    state: absent
    wait: True