---
- include_tasks: vpc.yml

- name: add default route to tgw for egress
  shell: |
    aws ec2 create-transit-gateway-route \
    --destination-cidr-block 0.0.0.0/0 \
    --transit-gateway-route-table-id {{ tgw_route_table }} \
    --transit-gateway-attachment-id {{ _egress_vpc_tgw_attachment_id }}
  register: _tgw_rt
  failed_when: (_tgw_rt.rc != 0) and ("RouteAlreadyExists" is not in _tgw_rt.stderr)
  changed_when: _tgw_rt.rc == 0
